<a href="https://colab.research.google.com/github/hotdog1029/deeplearning/blob/main/0_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

텐서(Tensor)란, '데이터를 표현하는 단위

# 스칼라(Scalar) 
스칼라는 우리가 흔히 알고 있는 상수값이다. 즉, 하나의 값을 표현할 때 1개의 수치로 표현한 것이다. pytorch 모듈을 이용해 import torch해주고 torch 내 텐서 메서드를 이용해 스칼라 값을 정의 할 수 있다.

In [1]:
import torch

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


스칼라 값 간의 사칙연산 수행 , 사칙연산은 +,-,*/를 이용해 계산할 수 있다.

In [4]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


스칼라 값 간의 사칙연산 역시 torch 모듈에 내장된 메서드를 이용해 계산할 수 있다.

In [8]:
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

# Vector
벡터는 하나의 값을 표현할 때 2개 이상의 수치로 표현한 것. 스칼라의 형태와 동일한 속성을 갖고 있지만, 여러 수치 값을 이용해 표현하는 방식

In [12]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)

tensor([1., 2., 3.])


In [13]:
vector2 = torch.tensor([4.,5.,6.])
print(vector2)

tensor([4., 5., 6.])


벡터 간의 사칙연산은 스칼라 사칙연산과 동일한 방식 , 여기서 곱셈과 나눗셈은 각 요소별로 연산됨

In [15]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [16]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [17]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [18]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


스칼라와 동일하게 똑같이 torch모듈에 내장된 메서드를 이용할 수 있다.

# 행렬(Matrix)
행렬은 2개 이상의 벡터 값을 통합해 구성된 값으로, 벡터 값 간 연산 속도를 빠르게 진행할 수 있는 선형 대수의 기본 단위

In [20]:
matrix1 = torch.tensor([[1.,2.],[3.,4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
matrix2 = torch.tensor([[5.,6.],[7.,8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


행렬 값 간의 사칙연산도 스칼라,벡터 사칙연산과 동일한 방식이다.

In [21]:
add_matrix = matrix1 + matrix2
print(add_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [22]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [23]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [24]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [33]:
torch.matmul(matrix1,matrix2)  # 다음과 같이 행렬 곱 연산은 torch.matmul을 이용해 실행 할 수 있다.

tensor([[19., 22.],
        [43., 50.]])

행렬을 2차원의 배열이라 표현할 수 있다면, 텐서는 2차원 이상의 배열이라 표현할 수 있다. 텐서의 파이토치 예제 역시 스칼라 벡터, 행렬과 같은 논리로 적용된다. 텐서 내 행렬 단위의 인덱스 간, 행렬 내 인덱스 간 원소끼리 계산되며 행렬 곱은 텐서 내 같은 행렬 단위의 인덱스 간에 계산된다.

In [27]:
tensor1 = torch.tensor([[[1.,2.],[3.,4.]],[[5.,6.],[7.,8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [28]:
tensor2 = torch.tensor([[[9.,10.],[11.,12.]],[[13.,14.],[15.,16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [29]:
print(tensor1 + tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [30]:
print(tensor1 - tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [31]:
print(tensor1 * tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [32]:
print(tensor1 / tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [35]:
torch.matmul(tensor1,tensor2)  # 행렬곱 표현도 가능

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])