<a href="https://colab.research.google.com/github/hotdog1029/deeplearning/blob/main/2_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# 데이터 설정
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True) # 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
b = torch.zeros(1, requires_grad=True) # 편향 b를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시

# optimizer 설정
optimizer = optim.SGD([W,b], lr = 0.01) # SGD는 경사 하강법의 일종이다. lr(lerning rate)는 학습률을 의미한다. 학습 대상인 W와 b가 SGD의 입력이 된다.

nb_epochs = 2000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs+1):
  # H(x) 계산
  hypothesis = x_train * W + b # 가설 세우기

  # cost(loss) 계산
  cost = torch.mean((hypothesis - y_train) ** 2) # 선형회귀의 비용함수에 해당되는 평균 제곱 오차를 선언

  # cost로 H(x) 개선
  optimizer.zero_grad() # gradient를 0으로 초기화
  cost.backward() # 비용함수를 미분하여 gradient 계산
  optimizer.step() # W와 b를 업데이트

  # 100번마다 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs,W.item(),b.item(),cost.item()))

# 선형회귀는 결국 원하는만큼 경사하강법을 반복하여 cost(loss)를 줄여나가 W(가중치)와 b(편향)을 구하는 것이다.
#  optimizer.zero_grad()는 미분값이 누적되는것을 방지하여 0으로 계속 초기화 시켜주기위함이다.
# requires_grad=True, backward() 등은 파이토치에서 제공하고 있는 자동 미분 기능을 수행하는 것이다.

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

In [ ]:
# 다중 선형 회귀(다수의 x로부터 y를 예측)

# 데이터 설정
x1_train = torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가충치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1,w2,w3,b], lr = 1e-5)

# 원하는 횟수만큼 경사하강법 반복
nb_epochs = 5000
for epoch in range(nb_epochs+1):
  # H(x) 계산
  hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번 마다 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/5000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/5000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/5000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/5000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/5000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/5000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/5000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/5000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/5000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/5000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/5000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390
Epoch 1100/5000 w1: 0.722 w2: 0.608 w3: 0.680 b: 0.009 Cost: 1.038574
Epoch 1200/5000 w1: 0.727 w2: 0.603 w3: 0.681 b: 0.010 Cost: 0.999884
Epoch 1300/5000 w1: 0.731 w2: 0.599 w3: 0.681 b: 0.010 Cost: 0.963217
Epoch 1400/5000 

In [ ]:
# nn.Module로 구현하는 선형 회귀

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 선언 및 초기화, 단순 선형 회귀이므로 input_dim = 1 ,output_dim = 1
model = nn.Linear(1,1) # model에는 가중치 W와 편향 b가 저장되어 있다.

# optimizer 설정 
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01) # 경사 하강법 SGD를 사용하고 lr(learning rate)은 0.01로 설정

# 경사하강법 2000번 반복
nb_epochs = 2000
for epoch in range(nb_epochs +1):

  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균 제곱오차함수

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))
print(list(model.parameters())) # W값이 2에 가깝고 b의 값이 0에 가까운것을 볼 수 있다.

Epoch    0/2000 Cost: 26.487640
Epoch  100/2000 Cost: 0.148082
Epoch  200/2000 Cost: 0.091506
Epoch  300/2000 Cost: 0.056545
Epoch  400/2000 Cost: 0.034941
Epoch  500/2000 Cost: 0.021592
Epoch  600/2000 Cost: 0.013342
Epoch  700/2000 Cost: 0.008245
Epoch  800/2000 Cost: 0.005095
Epoch  900/2000 Cost: 0.003148
Epoch 1000/2000 Cost: 0.001945
Epoch 1100/2000 Cost: 0.001202
Epoch 1200/2000 Cost: 0.000743
Epoch 1300/2000 Cost: 0.000459
Epoch 1400/2000 Cost: 0.000284
Epoch 1500/2000 Cost: 0.000175
Epoch 1600/2000 Cost: 0.000108
Epoch 1700/2000 Cost: 0.000067
Epoch 1800/2000 Cost: 0.000041
Epoch 1900/2000 Cost: 0.000026
Epoch 2000/2000 Cost: 0.000016
[Parameter containing:
tensor([[1.9954]], requires_grad=True), Parameter containing:
tensor([0.0105], requires_grad=True)]


In [ ]:
# nn.Module로 구현하는 다중 회귀

# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


print(list(model.parameters()))

Epoch    0/2000 Cost: 9229.115234
Epoch  100/2000 Cost: 1.889843
Epoch  200/2000 Cost: 1.805329
Epoch  300/2000 Cost: 1.725269
Epoch  400/2000 Cost: 1.649375
Epoch  500/2000 Cost: 1.577483
Epoch  600/2000 Cost: 1.509351
Epoch  700/2000 Cost: 1.444783
Epoch  800/2000 Cost: 1.383609
Epoch  900/2000 Cost: 1.325598
Epoch 1000/2000 Cost: 1.270651
Epoch 1100/2000 Cost: 1.218589
Epoch 1200/2000 Cost: 1.169212
Epoch 1300/2000 Cost: 1.122436
Epoch 1400/2000 Cost: 1.078090
Epoch 1500/2000 Cost: 1.036060
Epoch 1600/2000 Cost: 0.996226
Epoch 1700/2000 Cost: 0.958475
Epoch 1800/2000 Cost: 0.922675
Epoch 1900/2000 Cost: 0.888736
Epoch 2000/2000 Cost: 0.856582
[Parameter containing:
tensor([[0.7966, 0.6159, 0.6044]], requires_grad=True), Parameter containing:
tensor([-0.4597], requires_grad=True)]


In [ ]:
# 클래스로 구현

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 클래스를 구현
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

print(list(model.parameters()))

Epoch    0/2000 Cost: 14.315708
Epoch  100/2000 Cost: 0.000092
Epoch  200/2000 Cost: 0.000057
Epoch  300/2000 Cost: 0.000035
Epoch  400/2000 Cost: 0.000022
Epoch  500/2000 Cost: 0.000013
Epoch  600/2000 Cost: 0.000008
Epoch  700/2000 Cost: 0.000005
Epoch  800/2000 Cost: 0.000003
Epoch  900/2000 Cost: 0.000002
Epoch 1000/2000 Cost: 0.000001
Epoch 1100/2000 Cost: 0.000001
Epoch 1200/2000 Cost: 0.000000
Epoch 1300/2000 Cost: 0.000000
Epoch 1400/2000 Cost: 0.000000
Epoch 1500/2000 Cost: 0.000000
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
[Parameter containing:
tensor([[2.0001]], requires_grad=True), Parameter containing:
tensor([-0.0003], requires_grad=True)]
